version: '3.9'

services:
  bot:
    build: .
    ports:
      - "80:8080"
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
      TELEGRAM_THREAD_ID: "${TELEGRAM_THREAD_ID}"
      GITHUB_USERNAME_MAPPER: "/app/usernames.yaml"
    volumes:
      - ./usernames.yaml:/app/usernames.yaml